meta_product_name: "The Guild"
meta_title: "The Guild - The all-in-one place for guilds!"
meta_description: "The guild is a platform for guilds to manage their members, events, and chat with others, all in one place. No need to create multiple accounts or use multiple platforms, The Guild has it all!"
meta_image: "page-image.jpg"
